### ISSUE TITLE
setup screemshot when a test fail

### ISSUE THREAD

**Issue by edvasquezlondono** [ArturSpirin/test_junkie#38]
Hello, please add screenshot image when a test fail:
![image](https://user-images.githubusercontent.com/45776565/118002087-e7827c80-b30c-11eb-9f28-a9b559c385f3.png)
![image](https://user-images.githubusercontent.com/45776565/118002314-1e589280-b30d-11eb-8389-9301e5675349.png)
![image](https://user-images.githubusercontent.com/45776565/118002384-2d3f4500-b30d-11eb-89fd-d184440bce17.png)
![image](https://user-images.githubusercontent.com/45776565/118002478-43e59c00-b30d-11eb-90ef-e4159ed67f50.png)
![image](https://user-images.githubusercontent.com/45776565/118002516-4d6f0400-b30d-11eb-82ed-7136d21a1ea5.png)
first of all, Thanks.

**Comment by ArturSpirin** [comment]
@edvasquezlondono Test Junkie is a generic framework, meaning it can be used for things other than selenium tests where screenshot is not applicable. Test Junkie extends listeners to the user for this exact reason so this can be built in frameworks where its necessary. Listener class can be inherited, and you can add and overwrite methods from it, from your screenshots I see that you made direct changes to the underlying module for listener.py this is not how it was intended to be used. You want to subclass Listener class in your own (MyListener(Listener)) class and then make changes that make sense to have in your listener for your  current application. You can create multiple listener classes that way as well and they can be assigned independently to any test suite. https://www.test-junkie.com/documentation/#listeners
