### ISSUE TITLE
Hi Champion

### ISSUE THREAD

**Issue by YakirMoshe** [ArturSpirin/test_junkie#41]
### Describe desired feature

I wanted to ask how you can achieve the project you present on YouTube at:
Page Objects - Advanced Selenium WebDrvier Tutorial [Python]

I would love if you could email it to me or write me how to get this project done.
yakirm25@gmail.com
Many thanks in advance!!

### Any existing examples of such feature?
![Test Junkie](https://user-images.githubusercontent.com/49817134/139581116-e590b746-4ebd-4559-9cd5-14deba9e2c40.png)

**Comment by YakirMoshe** [comment]
![image](https://user-images.githubusercontent.com/49817134/139581787-8e56de61-3843-430b-8e83-16f3767cde33.png)

**Comment by YakirMoshe** [comment]
This is where the project can be found ?

**Comment by ArturSpirin** [comment]
@YakirMoshe I'm using this repository locally to test out deployments for test-junkie.com before I publish them. I'd have to take a look at the code to see if there is anything sensitive in there. If there is not much code to go through, I may share the repo. Will let you know in the coming days.

**Comment by YakirMoshe** [comment]
thank you very much for your contribution, I follow you after a lot of videos, I wanted to tell you that you are really a champion you explain very detailed and show step by step really clear also I do not really understand English I can learn from you !!
Huge thanks !

**Comment by ArturSpirin** [comment]
@YakirMoshe You can find the repository archived here https://drive.google.com/file/d/13Gb98n3VWKwBph0eRLzhsmkuw3i2RV_t/view?usp=sharing. I'm glad those videos are helpful, thanks for the feedback!

**Comment by YakirMoshe** [comment]
Thank you!
I in my work built a selenium infrastructure with JAVA, and in the new work want to set up a Python infrastructure with selenium, I really have no words you helped me a lot to understand things.

And another little question dude will you ever create
Selenium + python + api tutorial? ..
Because I've worked until now with Rest Assured

**Comment by YakirMoshe** [comment]
How can this be treated?
![image](https://user-images.githubusercontent.com/49817134/139856187-cc86b5ee-4471-4b94-96ec-d3019e27517d.png)

I tried "pip install src" but still do not resolve the issue

**Comment by YakirMoshe** [comment]
No matter bro I moved into another folder and gave it the whole path and it worked out, regarding the API do you have tutorials? (With Python + Selenium)

![image](https://user-images.githubusercontent.com/49817134/139862751-857aeb86-3d54-4833-801f-435eb7859a85.png)

**Comment by ArturSpirin** [comment]
@YakirMoshe I might make some API tutorial videos in the future. I would look at the requests module for Python, it will go a long way for you if you learn how to use it, not just for API testing but for development in general - its a good tool to know.

**Comment by YakirMoshe** [comment]
Got it, thank you so much for all your contribution!
And of course I keep following you and waiting for your tutorials for API :)
